hassio-addons/addon-ssh

ssh/Dockerfile

> hassio-cli was updated 21 days ago to 1.3.0 and has some bug fixes that work in the regular ssh addon. This change updates hassio-cli to 1.3.0

Update docker image to use hassio-cli 1.3.0

---

README.md

Remove reference to iFrame as the ingress sidebar should be the preferred approach.
None

📚Remove iframe reference due to ingress

---

README.md

> Add in limitation the need to use `root` username with rsync. It's not obvious and I've try to make it work without `root` before having confirmation on the community forum
> N/A

:books: Add limitation root with rsync

---

ssh/rootfs/etc/ssh/sshd_config

This will improve SSH connect speed, as the SSH server won't need to reverse-lookup the incoming address.
Currently it takes few seconds due to this setting, which may fail if DNS set does not have a DNS PTR resolution.
```
reverse mapping checking getaddrinfo for gigaman [192.168.10.3] failed.
```

Disable SSH DNS lookup

---

ssh/Dockerfile

https://github.com/home-assistant/cli/releases/tag/4.10.1

:arrow_up: Upgrades Home Assistant CLI to v4.10.1

---

ssh/Dockerfile
ssh/build.json

Bumps add-on base image to 9.1.4:
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.4
Additionally bumps openssl packages in order to be able to match upstream.

Upgrade add-on base image to 9.1.4

---

ssh/config.json

This PR grands the add-on access to the journald log files from the host system. This can be helpful when debugging/chasing issues with the system.

Add access to journald

---

ssh/Dockerfile

https://github.com/home-assistant/cli/releases/tag/4.11.1
https://github.com/home-assistant/cli/releases/tag/4.11.2

⬆️ Upgrades Home Assistant CLI to v4.11.2

---

ssh/Dockerfile

Upgrades Home Assistant CLI to v4.12.2
https://github.com/home-assistant/cli/releases/tag/4.12.2

⬆️ Upgrades Home Assistant CLI to v4.12.2

---

ssh/Dockerfile

https://github.com/home-assistant/cli/releases/tag/4.13.0
https://github.com/home-assistant/cli/releases/tag/4.14.0

⬆️ Upgrades Home Assistant CLI to v4.14.0

---

ssh/Dockerfile

Upgrades ttyd to a development version. To many bug fixes are in there, that are causing problems for this add-on. Therefore, making an exception to run a tested specific commit for ttyd.
fixes #320
might improve #330

Upgrade ttyd 62a5b63 & libwebsockets 4.2.1

---

README.md
ssh/.README.j2
ssh/DOCS.md
ssh/config.yaml
ssh/rootfs/etc/cont-init.d/ssh.sh

This removes the `i_like_to_be_pwned` configuration parameter and HIBP checks.
This functionality is now part of the Supervisor itself, and no longer needed in the add-on.

🔥 Remove hibp checks

---

README.md
ssh/DOCS.md
ssh/Dockerfile
ssh/requirements.txt

Upgrades for this tool have been incompatible for some time now; and therefore has been removed.

🔥 Remove homeassistant_cli

---

ssh/Dockerfile

Upgrades Home Assistant CLI to v4.15.1

⬆️ Upgrades Home Assistant CLI to v4.15.1

---

ssh/DOCS.md

The HaveIBeenPwned check is removed in v10.0.0.

Remove HaveIBeenPwned references

---

ssh/rootfs/etc/sudoers.d/ssh-agent-env

Add `--preserve-env=SSH_AUTH_SOCK` to the `sudo` invocation that switches to `root` immediately upon login (from, e.g. `hassio` user)
N.b. it's fine to leave this in by default, since if `allow_agent_forwarding` is false, the agent won't work.
fixes #367 SSH agent configuration isn't preserved

Preserve the SSH_AUTH_SOCK environment variable

---

ssh/DOCS.md

Explicitly state usernames will be converted to lower case.
Closes #395

📚 Add note on usernames

---

ssh/Dockerfile

Fix git URL for oh-my-zsh, it still used the old `git://` URLs structure

:ambulance: Fix git URL for oh-my-zsh

---

ssh/Dockerfile

- https://github.com/home-assistant/cli/releases/tag/4.16.0
- https://github.com/home-assistant/cli/releases/tag/4.16.1

⬆️ Upgrades Home Assistant CLI to v4.16.1

---

ssh/Dockerfile

https://github.com/home-assistant/cli/releases/tag/4.17.0

⬆️ Upgrades Home Assistant CLI to v4.17.0

---

ssh/Dockerfile

The `nmcli` has been put into a separate package in Alpine 3.16; and thus was lost on the base image upgrade in the last release.
This PR restores it.

:ambulance: Fix missing nmcli

---

ssh/Dockerfile

Upgrades Home Assistant CLI to v4.19.0

⬆️ Upgrades Home Assistant CLI to v4.19.0

---

ssh/Dockerfile

Upgrades mariadb-client to 10.6.9-r0

⬆️ Upgrades mariadb-client to 10.6.9-r0

---

ssh/rootfs/etc/profile.d/hassio.sh

With zsh, the window title is set to display the user, host, and path. This makes it happen for bash too, using the same format as it's with zsh.
The TERM cases where this is done come from Ubuntu 20.04 and CentOS 7 combined. (CentOS sets the title via `$PROMPT_COMMAND`, not `$PS1` though.)
None that I know of.

🪟 Set window title in bash prompt

---

ssh/rootfs/root/.zshrc

Adjust and fix `ha` CLI autocompletion caused by the change in:
https://github.com/home-assistant/cli/pull/367

🚑 Fix ha CLI autocompletion

---

ssh/Dockerfile

Bash completion is broken in the latest release. This PR fixes it.
```
~ $ ha <TAB> 
.bash_history  .config/       .lesshst       .ssh/          .viminfo       .zshrc         backup/        media/         ssl/           
.bash_profile  .gitconfig     .oh-my-zsh/    .tmux.conf     .vimrc         addons/        config/        share/
```
#460 fixed completion for `zsh` but not for `bash`.

Fix bash completion

---

ssh/rootfs/etc/profile.d/hassio.sh

`#` for root, `$` for non-root is a long standing tradition in bash and some other shells. Presenting `$` for root is kind of dangerous as it causes incorrect assumptions about the powers at hand.
I don't know but I suppose `/etc/profile.d` snippets are loaded by zsh as well, but the zsh prompt looks quite different; I believe it gets rewritten later on on purpose. And maybe the hash vs dollar tradition isn't a thing for it in the first place, so this change should be good from that point of view.

Fix bash; use hash mark in root prompt

---

ssh/rootfs/etc/ssh/sshd_config

```
(rec) +sntrup761x25519-sha512@openssh.com   -- kex algorithm to append
(rec) -diffie-hellman-group14-sha256        -- kex algorithm to remove
```
https://github.com/openssh/openssh-portable/blob/4922ac3be8a996780ef3dc220411da2e27c29d9c/sshd_config.5#L1045-L1050

Sync server `KexAlgorithms` with OpenSSH 9.1 and ssh-audit dev

---

ssh/rootfs/etc/ssh/ssh_config

```
-(rec) -diffie-hellman-group14-sha256               -- kex algorithm to remove
-(rec) -ecdh-sha2-nistp256                          -- kex algorithm to remove
-(rec) -ecdh-sha2-nistp384                          -- kex algorithm to remove
-(rec) -ecdh-sha2-nistp521                          -- kex algorithm to remove
-(rec) -ecdsa-sha2-nistp256                         -- key algorithm to remove
-(rec) -ecdsa-sha2-nistp256-cert-v01@openssh.com    -- key algorithm to remove
-(rec) -ecdsa-sha2-nistp384                         -- key algorithm to remove
-(rec) -ecdsa-sha2-nistp384-cert-v01@openssh.com    -- key algorithm to remove
-(rec) -ecdsa-sha2-nistp521                         -- key algorithm to remove
-(rec) …
```

Implement current ssh-audit dev client recommendations

---

ssh/rootfs/etc/ssh/sshd_config

For easier maintenance on version changes and crosschecking with ssh-audit, self/intent-documenting.
Subtle MACs order difference before and after in terms of ssh-audit output:
```
-(mac) hmac-sha2-512-etm@openssh.com         -- [info] available since OpenSSH 6.2
-(mac) hmac-sha2-256-etm@openssh.com         -- [info] available since OpenSSH 6.2
(mac) umac-128-etm@openssh.com              -- [info] available since OpenSSH 6.2
+(mac) hmac-sha2-256-etm@openssh.com         -- [info] available since OpenSSH 6.2
+(mac) hmac-sha2-512-etm@openssh.com         -- [info] available since OpenSSH 6.2
```
[autolink-references]: …

Specify server MACs and KexAlgos in terms of removals

---

README.md
ssh/.README.j2
ssh/DOCS.md
ssh/config.yaml
ssh/rootfs/etc/s6-overlay/s6-rc.d/init-docker/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/init-mosquitto/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/init-mysql/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/init-ssh/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/sshd/finish
ssh/rootfs/etc/s6-overlay/s6-rc.d/sshd/run
ssh/rootfs/etc/s6-overlay/s6-rc.d/ttyd/finish
ssh/rootfs/etc/s6-overlay/s6-rc.d/ttyd/run
ssh/rootfs/usr/local/bin/docker
ssh/rootfs/usr/local/bin/reboot
ssh/rootfs/usr/local/bin/shutdown

The naming of this add-on often needs to be clarified with the official core add-on. While they are similar, the community version offers more capabilities and access.
Initially, the Core version didn't carry a web terminal. Hence the name in the past was different. Renaming it to `Advanced SSH & Web Terminal`, will provide an additional difference in naming and functionality.

Rename add-on to Advanced SSH & Web Terminal

---

ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run

Move Environment file setup after the folder config, tested and should work ok.  I believe that the original testing is likely to do with using a password rather than key.
Should fix #551 fix #552

🚑 Move env setup after folder creation

---

ssh/rootfs/etc/s6-overlay/s6-rc.d/ttyd/run

SSIA, the latest ttyd makes the terminal read-only by default. However, our use case it to actually being able to type into it :)
This PR makes the add-on compatible with the latest ttyd

Make ttyd writable

---

ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run

`${dir}` doesn't belong in this message.

Fix unbound variable in log warning message

---

ssh/rootfs/etc/ssh/sshd_config

Disable the `chacha20-poly1305@openssh.com` cipher to address [CVE-2023-48795](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-48795).

Disable the chacha20-poly1305@openssh.com cipher, CVE-2023-48795

---

ssh/rootfs/etc/s6-overlay/s6-rc.d/ttyd/run
ssh/rootfs/root/.tmux.conf

Set a `TTYD` environment variable for the ttyd daemon and disable mouse mode in tmux if `$TTYD` is set.
Fixes #624

Disable tmux mouse mode when running under ttyd

---

ssh/DOCS.md
ssh/Dockerfile

Seems like the `ps` command included in Alpine is not enough anymore.
~~Adding this to the documentation, but maybe it makes more sense to have it in the Dockerfile?~~
Adding `procps` to the Dockerfile, so that's included and Visual Studio Code remote-ssh can connect out-of-the-box
Fixes https://github.com/hassio-addons/addon-ssh/issues/722

Include procps by default for Visual Studio Code

---

ssh/rootfs/root/.tmux.conf

xclip needs access to your $DISPLAY, so if it's not set, don't try to use it.
Fixes #719

Don't attempt to use xclip when X is not available
