hassio-addons/addon-ssh

ssh/config.json
=> Add audio/UART permissions to facilitate better addon debugging.

ssh/Dockerfile
=> Upgrades OpenSSL to 1.0.2p-r0

ssh/Dockerfile
This PR upgrades hass-cli to 0.2.0
NA
=> ⬆️ Upgrades homeassistant_cli to 0.2.0

ssh/Dockerfile
Updates Home Assistant CLI to [v0.3.0](https://github.com/home-assistant/home-assistant-cli/releases/tag/0.3.0)
=> Update hass-cli to 0.3.0

ssh/Dockerfile
New release:
https://github.com/home-assistant/hassio-cli/releases/tag/2.0.1
<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio-cli">home-assistant/hassio-cli</a></strong></div><div>:white_square_button: Hass.io command line interface - home-assistant/hassio-cli</div></blockquote>
=> :arrow_up: Update hassio-cli to v2.0.1

ssh/rootfs/root/.zprofile, ssh/rootfs/root/.zshrc
Fixes non-interactive shell command usage with container issue #77
=> :ambulance: Fix for non interactive usage

.github/config.yml, .github/settings.yml, ssh/rootfs/etc/cont-init.d/ssh.sh, ssh/rootfs/etc/cont-init.d/user.sh
=> :ambulance: Spelling and grammar fixes

ssh/Dockerfile
docker completions are nice to have around.
=> Include docker completions

ssh/.README.j2
=> :pencil2: Fix typo in README

ssh/DOCS.md
Clarify config of SSH keys
#144
=> ✏ Clarify SSH Keys config

ssh/rootfs/etc/cont-init.d/ssh.sh
Add log message to state external SSH only available if Network port defined.
None
=> 📚Add message for network access

ssh/Dockerfile, ssh/build.json
Upgrades the add-on base image, bringing up Alpine Linux to 3.13.
=> Upgrade add-on base image to 9.1.1

ssh/Dockerfile
https://github.com/tsl0922/ttyd/releases/tag/1.6.3
=> Upgrade ttyd 1.6.3 & libwebsockets 4.1.4

ssh/Dockerfile, ssh/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
=> Upgrade add-on base image to 9.1.2

ssh/Dockerfile
=> :arrow_up: Upgrades docker to 20.10.3-r0

.github/workflows/ci.yaml, ssh/config.json
Updates add-on configuration to be compatible with Supervisor 2021.2 and newer.
=> Update add-on configuration for Supervisor 2021.2

ssh/Dockerfile
=> :arrow_up: Upgrades git to 2.30.1-r0

ssh/config.json
This parameter is no longer needed.
=> Remove full access parameter

ssh/Dockerfile
=> :arrow_up: Upgrades python3 to 3.8.7-r1

ssh/Dockerfile
=> ⬆️  Upgrades python3 to 3.8.8-r0

ssh/Dockerfile
=> ⬆️  Upgrades git to 2.30.2-r0

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.11.0
=> ⬆️ Upgrades Home Assistant CLI to v4.11.0

ssh/Dockerfile
=> ttyd renamed their main branch upstream

ssh/Dockerfile, ssh/build.json
Upgrades add-on base image to v9.1.5
=> ⬆️  Upgrades add-on base image to v9.1.5

ssh/Dockerfile
=> ⬆️ Upgrades docker to 20.10.3-r1

.github/workflows/ci.yaml
https://github.com/frenck/action-addon-linter/releases/tag/v2.1.0
=> Upgrade add-on linter to 2.1.0

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.11.3
=> ⬆️ Upgrades Home Assistant CLI to v4.11.3

ssh/Dockerfile
=> ⬆️ Upgrades openssh to 8.4_p1-r3

ssh/Dockerfile, ssh/build.json
Upgrade add-on base image to 9.1.6
=> Upgrade add-on base image to 9.1.6

ssh/Dockerfile
Upgrades networkmanager to 1.26.6-r0
=> ⬆️ Upgrades networkmanager to 1.26.6-r0

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.12.0
=> ⬆️ Upgrades Home Assistant CLI to v4.12.0

ssh/Dockerfile, ssh/build.json
Upgrades add-on base image to v9.2.0
=> Upgrades add-on base image to v9.2.0

ssh/Dockerfile
Upgrades mariadb-client to 10.5.9-r0
=> ⬆️ Upgrades mariadb-client to 10.5.9-r0

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.12.1
=> ⬆️ Upgrades Home Assistant CLI to v4.12.1

ssh/Dockerfile
Upgrades bind-tools to 9.16.15-r1
=> ⬆️ Upgrades bind-tools to 9.16.15-r1

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.12.3
=> ⬆️ Upgrades Home Assistant CLI to v4.12.3

ssh/Dockerfile, ssh/build.json
Upgrades add-on base image to v9.2.2
=> ⬆️ Upgrades add-on base image to v9.2.2

ssh/Dockerfile, ssh/build.json
Upgrades add-on base image to v10.0.0
Bumping Alpine Linux to 3.14
=> ⬆️ Upgrades add-on base image to v10.0.0

ssh/Dockerfile
Upgrades mariadb-client to 10.5.12-r0
=> ⬆️ Upgrades mariadb-client to 10.5.12-r0

ssh/Dockerfile
=> ⬆️ Upgrades rsync to 3.2.3-r4

ssh/Dockerfile, ssh/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v10.0.1
=> ⬆️ Upgrades add-on base image to v10.0.1

ssh/config.json
=> 🏎 Enable streaming mode for Ingress

ssh/Dockerfile, ssh/build.json
Upgrades add-on base image to 10.2.2
=> ⬆️ Upgrades add-on base image to 10.2.2

ssh/Dockerfile
=> ⬆️ Upgrades docker to 20.10.9-r0

ssh/Dockerfile
=> ⬆️ Upgrades openssl to 1.1.1l-r0

ssh/Dockerfile
Upgrades bind-tools to 9.16.20-r1
=> ⬆️ Upgrades bind-tools to 9.16.20-r1

ssh/Dockerfile
=> ⬆️ Upgrades openssh to 8.6_p1-r3

ssh/Dockerfile
=> ⬆️ Upgrades vim to 8.2.3437-r0

ssh/Dockerfile
Upgrades mariadb-client to 10.5.13-r0
=> ⬆️ Upgrades mariadb-client to 10.5.13-r0

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 10.2.3
=> ⬆️ Upgrades add-on base image to 10.2.3

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 11.0.0
=> ⬆️ Upgrades add-on base image to 11.0.0

ssh/Dockerfile
Upgrades TTYd to 3e37e33, which should resolve some WebGL issues.
=> ⬆️ Upgrades ttyd to 3e37e33

ssh/rootfs/root/.zshrc
Left behind when I cleaned it up.
=> 🔥 Remove left over hass-cli auto completion

LICENSE.md, README.md, ssh/.README.j2, ssh/DOCS.md
=> :fireworks: Updates maintenance/license year to 2022

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 11.0.1
=> ⬆️ Upgrades add-on base image to 11.0.1

ssh/Dockerfile
Upgrades bind-tools to 9.16.25-r0
=> ⬆️ Upgrades bind-tools to 9.16.25-r0

ssh/Dockerfile
=> ⬆️ Upgrades bluez to 5.63-r0

ssh/Dockerfile
Upgrades libxml2-utils to 2.9.13-r0
=> ⬆️ Upgrades libxml2-utils to 2.9.13-r0

ssh/Dockerfile
=> ⬆️ Upgrades vim to 8.2.4173-r0

ssh/Dockerfile
=> ⬆️ Upgrades zsh to 5.8.1-r0

ssh/Dockerfile
Upgrades zsh-syntax-highlighting to 0.7.1-r1
=> ⬆️ Upgrades zsh-syntax-highlighting to 0.7.1-r1

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 11.1.0
=> ⬆️ Upgrades add-on base image to 11.1.0

ssh/build.yaml, ssh/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
=> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 11.1.2
=> ⬆️ Upgrades add-on base image to 11.1.2

ssh/Dockerfile
Upgrades zlib-dev to 1.2.12-r1
=> ⬆️ Upgrades zlib-dev to 1.2.12-r1

ssh/Dockerfile
Upgrades bind-tools to 9.16.27-r0
=> ⬆️ Upgrades bind-tools to 9.16.27-r0

ssh/Dockerfile
=> ⬆️ Upgrades bluez to 5.64-r0

ssh/Dockerfile
=> ⬆️ Upgrades vim to 8.2.4836-r0

ssh/Dockerfile
=> ⬆️ Upgrades git to 2.34.2-r0

ssh/Dockerfile
Upgrades mariadb-client to 10.6.7-r0
=> ⬆️ Upgrades mariadb-client to 10.6.7-r0

ssh/Dockerfile
=> ⬆️ Upgrades openssl to 1.1.1n-r0

ssh/Dockerfile
Updates `ttyd` to a version that has some bug fixes. Unfortunately, we have to pin to a git commit to solve WebGL issues.
=> ⬆️ Upgrades ttyd to 2b4dbac

ssh/DOCS.md
=> :books: Use new My Home Assistant link format

ssh/Dockerfile
<https://github.com/home-assistant/cli/releases/tag/4.18.0>
=> ⬆️ Upgrades Home Assistant CLI to v4.18.0

.github/SECURITY.md, README.md, ssh/DOCS.md, ssh/rootfs/etc/services.d/sshd/finish, ssh/rootfs/etc/services.d/ttyd/finish
=> Spelling fixes

ssh/Dockerfile, ssh/build.yaml
Upgrades add-on base image to 12.2.1
=> ⬆️ Upgrades add-on base image to 12.2.1

ssh/rootfs/usr/bin/hassio
=> Remove deprecated `hassio` command

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 12.2.2

ssh/Dockerfile
=> ⬆️ Upgrades zlib-dev to 1.2.12-r2

ssh/Dockerfile
Updates ttyd to 1.7.0
<https://github.com/tsl0922/ttyd/releases/tag/1.7.0>
Upgrades libwebsockets to 4.3.2 in the process, as that is what ttyd needs at this point.
=> ⬆️ Upgrades ttyd to 1.7.0

ssh/Dockerfile
Upgrades zlib-dev to 1.2.12-r3
=> ⬆️ Upgrades zlib-dev to 1.2.12-r3

ssh/Dockerfile
https://github.com/tsl0922/ttyd/releases/tag/1.7.1
=> ⬆️ Upgrades ttyd to 1.7.1

ssh/Dockerfile
Upgrades docker to 20.10.18-r0
=> ⬆️ Upgrades docker to 20.10.18-r0

ssh/Dockerfile
Upgrades libxml2-utils to 2.9.14-r1
=> ⬆️ Upgrades libxml2-utils to 2.9.14-r1

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 12.2.4

README.md, ssh/.README.j2, ssh/DOCS.md
=> Grammar fixes

ssh/Dockerfile
=> ⬆️ Upgrades Home Assistant CLI to v4.21.0

ssh/Dockerfile
=> ⬆️ Upgrades docker to 20.10.20-r0

ssh/Dockerfile
=> ⬆️ Upgrades git to 2.36.3-r0

ssh/Dockerfile
=> ⬆️ Upgrades mariadb-client to 10.6.10-r0

ssh/Dockerfile
=> ⬆️ Upgrades bind-tools to 9.16.33-r0

ssh/Dockerfile
=> ⬆️ Upgrades rsync to 3.2.7-r0

ssh/Dockerfile
=> ⬆️ Upgrades libxml2-utils to 2.9.14-r2

ssh/Dockerfile
https://github.com/tsl0922/ttyd/releases/tag/1.7.2
=> ⬆️ Upgrades ttyd to 1.7.2

ssh/rootfs/etc/cont-init.d/ssh.sh
=> ✏️ Fix typo in SSH key or password missing error

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.22.0
=> ⬆️ Upgrades Home Assistant CLI to v4.22.0

ssh/Dockerfile
=> ⬆️ Upgrades sudo to 1.9.12-r1

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 12.2.6

ssh/Dockerfile
https://github.com/home-assistant/cli/releases/tag/4.23.0
=> ⬆️ Upgrades Home Assistant CLI to v4.23.0

ssh/Dockerfile
=> ⬆️ Upgrades python3 to 3.10.8-r0

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 12.2.7

ssh/Dockerfile, ssh/build.yaml
Upgrades the add-on base image to 13.0.0, based on Alpine 3.17
=> ⬆️ Upgrades add-on base image to 13.0.0

ssh/Dockerfile
=> ⬆️ Upgrades git to 2.38.2-r0

ssh/Dockerfile
Upgrades docker to 20.10.21-r2
=> ⬆️ Upgrades docker to 20.10.21-r2

ssh/Dockerfile
=> ⬆️ Upgrades python3 to 3.10.9-r1

ssh/Dockerfile
=> ⬆️ Upgrades sqlite to 3.40.1-r0

ssh/Dockerfile
Upgrades networkmanager-cli to 1.40.8-r0
=> ⬆️ Upgrades networkmanager-cli to 1.40.8-r0

ssh/Dockerfile
Upgrades bind-tools to 9.18.10-r0
=> ⬆️ Upgrades bind-tools to 9.18.10-r0

LICENSE.md, README.md, ssh/.README.j2, ssh/DOCS.md
=> :fireworks: Updates maintenance/license year to 2023

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 13.0.1

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 13.1.0

ssh/Dockerfile
=> ⬆️ Upgrades git to 2.38.3-r1

ssh/Dockerfile
https://github.com/tsl0922/ttyd/releases/tag/1.7.3
=> ⬆️ Upgrades ttyd to 1.7.3

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 13.1.2

ssh/Dockerfile, ssh/build.yaml
=> ⬆️ Upgrades add-on base image to 13.1.3

ssh/DOCS.md
Fixes a broken URL in the documentation.
=> Fix broken URL

ssh/build.yaml, ssh/config.yaml
=> :toilet: Move away from Codenotary

ssh/build.yaml, ssh/config.yaml
This reverts commit f6b8e1768710b39c1b27a85526d79fccd671ec93.
Can't move away at this point, this has to await for an upstream change.
=> Revert ":toilet: Move away from Codenotary (#522)"

ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run, ssh/rootfs/etc/ssh/sshd_config, ssh/rootfs/etc/sudoers.d/ssh-agent-env
Similar change to: <https://github.com/home-assistant/addons/pull/2875>
=> Allow HA commands without an interactive shell

README.md, ssh/build.yaml, ssh/config.yaml
=> Drop support for armhf & i386

ssh/config.yaml, ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
Implements: <https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/>
=> Add support for public add-on configuration access

ssh/DOCS.md
RSA has–longtime-been deprecated.…
Changes to the document reflecting the procedure of generating and inserting the correct ed25519 key.
(If some Mac and Windows could contribute the procedures, on their respective platform, that would be great!)
> ([Github link][#354, #426] (And probably some other) related issues or pull requests)
=> Update SSH documentation configuration example

ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
=> Make vscode server data persistent

LICENSE.md, README.md, ssh/.README.j2, ssh/DOCS.md
=> :fireworks: Updates maintenance/license year to 2024

ssh/Dockerfile
=> Fix procps -> procps-ng
